### ISSUE TITLE
Wrong class installed via composer

### ISSUE THREAD

**Issue by ItSupportRenovatioTrading** [josantonius/php-session#19]
Hi, i'm getting a wrong class when I try to install this lib in my project.
I am using php 7.4
I run `composer require josantonius/session --prefer-source`  and I get this class: 

![image](https://user-images.githubusercontent.com/108864388/185237972-561490da-5926-470d-a89f-86aebf7e0cda.png)

which is "slightly" different from this:

![image](https://user-images.githubusercontent.com/108864388/185238100-26746bab-7c5f-45a0-8270-ced1792b02e2.png)

**Comment by josantonius** [comment]
That is correct. For PHP 7.4 the last available version is [1.1.9](https://github.com/josantonius/php-session/tree/1.1.9) (deprecated). As of version v2.0.0 it was completely restructured, as you can see in the [CHANGELOG](https://github.com/josantonius/php-session/blob/main/CHANGELOG.md#119-2022-06-21).

**Comment by ItSupportRenovatioTrading** [comment]
Thank you! I saw now the requirements too

![image](https://user-images.githubusercontent.com/108864388/185242153-f570f916-9fd1-44bc-b29a-68f775e8ee70.png)

Is there a chance for a version compatible with php 7.4 ?

**Comment by josantonius** [comment]
It is not ideal, but you could replace the code in the files. By removing the mixed data types and making a few small changes, it would already be compatible with PHP 7.4 (tests will not work).

I share with you the modified files 😉 

[Session.txt](https://github.com/josantonius/php-session/files/9366280/Session.txt)
[Facades-Session.txt](https://github.com/josantonius/php-session/files/9366282/Facades-Session.txt)

**Comment by ItSupportRenovatioTrading** [comment]
Thank you so much! I appreciate!
