### ISSUE TITLE
Composer require not installing the github version.

### ISSUE THREAD

**Issue by iLapaa** [josantonius/php-session#8]
Im new with composer and i started using your library but when i install it via composer it doesnt give me the github version, i always need to replace the Session.php with your github Session.php
![image](https://user-images.githubusercontent.com/40744610/153498223-9f765781-354d-4114-a31f-8dc443e6ed24.png)

**Comment by NaokiStark** [comment]
This needs to update to 1.1.8 but composer.json says 
```json
"require": {
   "php": "^5.6 || ^7.0"
},
```
I applied the 1.1.8 in my composer.json and ignored the php requirement (`composer update --ignore-platform-reqs`), this is not ideal but resolves the problem temporary (⚠️⚠️)

**Comment by josantonius** [comment]
I have not checked this but it should be fixed using version 1.1.9.
